"""
Film Scripts — the creative direction for every article's short film.

Each film follows the Ace Cafe formula: the article's most cinematic
narrative, subdivided into 6 scenes (FLUX photoreal still + Wan
motion), silent-film captions, a mood-matched score, and scene-cued
sound effects.

Fields per film:
    title_lines  - two lines for the opening title card
    subtitle     - italic line under the title
    mood         - score style: rockabilly | western | elegant_waltz | epic
    band_in      - scene index (0-based) where the music fully arrives
    sfx          - {scene_index: effect} cues: hoofbeats | ticks |
                   rain | wind | engine
    thumb_scene  - scene id used for the poster/thumbnail
    scenes       - id, seed, flux_prompt, motion_prompt, caption, eyebrow
"""

# Per-film photographic language
_K = "shot on 35mm Kodachrome film, documentary photography, realistic proportions, natural muted colors, film grain"

FILMS = {

    # ── DENIM: the 1873 copper rivet story ──────────────────────────
    "denim-and-the-rider-how-jeans-were-born-in-the-saddle": {
        "title_lines": ("THE RIVET THAT", "WON THE WEST"),
        "subtitle": "A true story from 1873",
        "mood": "western",
        "band_in": 2,
        "sfx": {0: "hoofbeats", 2: "ticks", 3: "hoofbeats", 4: "hoofbeats"},
        "thumb_scene": "05_drive",
        "scenes": [
            {"id": "01_range", "seed": 1873,
             "flux_prompt": "A cowboy on horseback on the open Nevada range at dusk, cattle herd in the far background, wide shot, warm dusty golden light, 1870s American West, " + _K,
             "motion_prompt": "the horse walks steadily, dust drifts across the range, the cowboy sways in the saddle",
             "caption": "Nevada, 1873.\nA cowboy's pockets kept tearing.",
             "eyebrow": "A TRUE STORY"},
            {"id": "02_torn", "seed": 1874,
             "flux_prompt": "Close-up of work-worn hands holding torn denim trousers, a ripped pocket seam, rough fabric texture, warm lamplight, 1870s, " + _K,
             "motion_prompt": "the hands turn the torn fabric over, examining the ripped seam",
             "caption": "Tools fell. Seams ripped.\nNothing survived the saddle.",
             "eyebrow": "THE PROBLEM"},
            {"id": "03_rivet", "seed": 1875,
             "flux_prompt": "A tailor at a wooden workbench hammering a small copper rivet into denim fabric, tools and rivets scattered, warm oil-lamp light, 1870s workshop, medium shot, " + _K,
             "motion_prompt": "the hammer strikes the rivet, the tailor works with focused precision",
             "caption": "A tailor tried something mad:\ncopper rivets in cloth.",
             "eyebrow": "THE FIX"},
            {"id": "04_saddle", "seed": 1876,
             "flux_prompt": "A cowboy in riveted denim jeans swinging up into a horse's saddle at a ranch, copper rivets glinting on the pockets, morning light, medium-wide shot, " + _K,
             "motion_prompt": "the cowboy mounts the horse, the horse steps sideways, he settles into the saddle",
             "caption": "14-hour days in the saddle.\nThe rivets held.",
             "eyebrow": "THE TEST"},
            {"id": "05_drive", "seed": 1877,
             "flux_prompt": "A cattle drive across a dusty plain, several cowboys in denim riding through golden dust clouds, epic wide shot, low sun, " + _K,
             "motion_prompt": "the herd moves forward, riders ride through the dust, hats and denim in the golden haze",
             "caption": "Desert thorns. Trail dirt.\nDenim outlived them all.",
             "eyebrow": "THE PROOF"},
            {"id": "06_icon", "seed": 1878,
             "flux_prompt": "A young man in blue jeans and white t-shirt leaning against a vintage motorcycle, 1950s American street, james dean style, cool confident posture, " + _K,
             "motion_prompt": "he looks up slowly, wind moves his hair, cigarette smoke drifts",
             "caption": "80 years later, rebellion\nwore the same rivets.",
             "eyebrow": "THE ICON"},
        ],
    },

    # ── LEH-LADAKH: the Himalayan ride ──────────────────────────────
    "leh-ladakh-the-ride-that-changes-everything": {
        "title_lines": ("THE RIDE ABOVE", "THE CLOUDS"),
        "subtitle": "Leh–Ladakh, 18,000 feet",
        "mood": "epic",
        "band_in": 1,
        "sfx": {0: "engine", 1: "wind", 2: "engine", 3: "engine",
                4: "wind", 5: "engine"},
        "thumb_scene": "04_hairpins",
        "scenes": [
            {"id": "01_road", "seed": 3501,
             "flux_prompt": "A lone motorcyclist on a winding Himalayan mountain road, immense snow-capped peaks towering above, vast scale, tiny rider in epic landscape, super wide shot, cold clear light, Ladakh India, " + _K,
             "motion_prompt": "the motorcycle moves steadily along the winding road, clouds drift over the peaks",
             "caption": "The Himalayas.\nOne rider. One machine.",
             "eyebrow": "18,000 FEET"},
            {"id": "02_flags", "seed": 3502,
             "flux_prompt": "Colorful Tibetan prayer flags strung across a high mountain pass road, a motorcycle approaching in the distance, wind-whipped flags in foreground, Ladakh, " + _K,
             "motion_prompt": "the prayer flags whip and flutter hard in the wind, the motorcycle slowly approaches",
             "caption": "Thin air. Broken roads.\nThe most beautiful ride on earth.",
             "eyebrow": "THE ASCENT"},
            {"id": "03_river", "seed": 3503,
             "flux_prompt": "A motorcyclist crossing a shallow glacier river ford on a mountain road, water splashing around the wheels, rocky Himalayan terrain, action shot, " + _K,
             "motion_prompt": "the motorcycle pushes through the water, splashes rise from the wheels, the rider balances",
             "caption": "Glacier rivers cross the road.\nYou ride through them.",
             "eyebrow": "THE CROSSING"},
            {"id": "04_hairpins", "seed": 3504,
             "flux_prompt": "Aerial view of dramatic switchback hairpin bends climbing a Himalayan mountainside, a tiny motorcycle ascending the loops, vast scale, high altitude desert, " + _K,
             "motion_prompt": "the tiny motorcycle climbs through the hairpin bends, shadows of clouds move across the mountain",
             "caption": "21 hairpins to the top\nof the world.",
             "eyebrow": "KHARDUNG LA"},
            {"id": "05_summit", "seed": 3505,
             "flux_prompt": "A motorcyclist standing at a Himalayan summit marker surrounded by thousands of prayer flags, arms raised in triumph, vast valley far below, golden light, " + _K,
             "motion_prompt": "the rider raises both arms in triumph, prayer flags whip around him, clouds move below",
             "caption": "Every rider who climbs it\ncomes down someone else.",
             "eyebrow": "THE SUMMIT"},
            {"id": "06_sunset", "seed": 3506,
             "flux_prompt": "A motorcyclist silhouetted against a golden sunset over Himalayan peaks, riding along a ridge road into the light, epic wide shot, " + _K,
             "motion_prompt": "the motorcycle rides toward the sunset, the golden light flares, mountains fade into haze",
             "caption": "You don't conquer Ladakh.\nIt rewards who you become.",
             "eyebrow": "THE RETURN"},
        ],
    },

    # ── HERMÈS: the harness maker of Paris ──────────────────────────
    "hermes-from-horse-harnesses-to-high-fashion": {
        "title_lines": ("THE HARNESS MAKER", "OF PARIS"),
        "subtitle": "Paris, 1837",
        "mood": "elegant_waltz",
        "band_in": 1,
        "sfx": {0: "hoofbeats", 1: "ticks", 4: "ticks"},
        "thumb_scene": "03_saddle",
        "scenes": [
            {"id": "01_carriages", "seed": 1837,
             "flux_prompt": "Horse-drawn carriages rolling down a Paris boulevard in the 1880s, gas lamps, elegant facades, pedestrians in period dress, wide evening shot, " + _K,
             "motion_prompt": "a carriage rolls past, the horses trot, pedestrians walk along the boulevard",
             "caption": "Paris, 1837.\nEvery carriage needed a harness.",
             "eyebrow": "A TRUE STORY"},
            {"id": "02_stitch", "seed": 1838,
             "flux_prompt": "A leather craftsman at a wooden bench saddle-stitching a harness strap with two needles, awls and waxed thread, warm atelier light, close medium shot, " + _K,
             "motion_prompt": "the craftsman's hands pull the two-needle stitch tight, thread draws through leather",
             "caption": "Thierry Hermès stitched\nfor the finest stables.",
             "eyebrow": "THE WORKSHOP"},
            {"id": "03_saddle", "seed": 1839,
             "flux_prompt": "A gleaming finished leather saddle on a wooden stand in a Paris atelier, brass fittings shining, tools hung on the wall behind, warm golden light, " + _K,
             "motion_prompt": "the camera slowly orbits the saddle, light gleams across the polished leather",
             "caption": "Two needles. One thread.\nThe saddle stitch never slips.",
             "eyebrow": "THE CRAFT"},
            {"id": "04_scarf", "seed": 1840,
             "flux_prompt": "An elegant woman in 1930s dress with a silk scarf stepping out of a vintage car outside a Paris boutique, doorman holding the door, " + _K,
             "motion_prompt": "her silk scarf flutters as she steps out, she walks toward the boutique",
             "caption": "When cars replaced horses,\nthe craft found new hands.",
             "eyebrow": "THE TURN"},
            {"id": "05_bag", "seed": 1841,
             "flux_prompt": "Craftsman's hands polishing a structured leather handbag on a workbench, orange boxes stacked behind, warm atelier light, close shot, " + _K,
             "motion_prompt": "the hands polish the leather in slow circles, the bag's surface begins to glow",
             "caption": "The same stitch now closed\nthe world's most wanted bag.",
             "eyebrow": "THE KELLY"},
            {"id": "06_maison", "seed": 1842,
             "flux_prompt": "An elegant Parisian boutique window at dusk, orange gift boxes and a leather bag lit warmly in the display, reflections of the street, " + _K,
             "motion_prompt": "reflections of passing people drift across the glass, the display light glows steadily",
             "caption": "The horse never left.\nIt lives in every stitch.",
             "eyebrow": "THE HOUSE"},
        ],
    },

    # ── SADDLEBAG: from war horse to Birkin ─────────────────────────
    "the-saddlebag-from-horse-leather-to-high-fashion": {
        "title_lines": ("FROM WAR HORSE", "TO BIRKIN"),
        "subtitle": "Fashion's greatest origin story",
        "mood": "elegant_waltz",
        "band_in": 2,
        "sfx": {0: "hoofbeats", 1: "hoofbeats", 3: "ticks"},
        "thumb_scene": "02_courier",
        "scenes": [
            {"id": "01_persia", "seed": 501,
             "flux_prompt": "An ancient Persian cavalry rider with leather pouches strapped to his horse, dramatic desert landscape, bronze armor detail, low golden sun, " + _K,
             "motion_prompt": "the horse canters forward, the leather pouches sway with the motion",
             "caption": "Persia, 500 BC.\nWar rode with leather.",
             "eyebrow": "A TRUE STORY"},
            {"id": "02_courier", "seed": 502,
             "flux_prompt": "A medieval courier galloping hard on horseback, saddlebags bouncing, a stone castle on the hill behind, dramatic motion, " + _K,
             "motion_prompt": "the horse gallops at full speed, the saddlebags bounce, the courier leans forward",
             "caption": "Kings' letters crossed empires\nin a horseman's bags.",
             "eyebrow": "THE COURIER"},
            {"id": "03_west", "seed": 503,
             "flux_prompt": "Close-up of a tooled leather saddlebag on a cowboy's horse, intricate hand-tooled patterns, dusty ranch background, warm light, " + _K,
             "motion_prompt": "the horse shifts its weight, the tooled leather catches the light",
             "caption": "The frontier tooled its\nwhole life into two bags.",
             "eyebrow": "THE WEST"},
            {"id": "04_atelier", "seed": 504,
             "flux_prompt": "A Paris leather atelier, a craftsman shaping a structured handbag from saddle leather, patterns and tools on the bench, warm light, " + _K,
             "motion_prompt": "the craftsman's hands shape and press the leather, turning the bag carefully",
             "caption": "In Paris, saddle makers\nturned to handbags.",
             "eyebrow": "THE ATELIER"},
            {"id": "05_kelly", "seed": 505,
             "flux_prompt": "An elegant woman in a 1950s suit carrying a structured leather handbag on a Paris street, photographers in the background, " + _K,
             "motion_prompt": "she walks gracefully past, holding the bag, flashbulbs flicker behind",
             "caption": "A princess made one bag\nthe most famous on earth.",
             "eyebrow": "THE KELLY"},
            {"id": "06_legacy", "seed": 506,
             "flux_prompt": "A luxury boutique window with iconic structured handbags dramatically lit, evening, elegant street reflection, " + _K,
             "motion_prompt": "the display lights glow, reflections of the street move across the glass",
             "caption": "Every it-bag began\nstrapped to a horse.",
             "eyebrow": "THE LEGACY"},
        ],
    },

    # ── POLO SHIRT ──────────────────────────────────────────────────
    "the-polo-shirt-from-horseback-to-high-street": {
        "title_lines": ("THE COLLAR THAT", "WOULD NOT BEHAVE"),
        "subtitle": "India, 1859",
        "mood": "elegant_waltz",
        "band_in": 2,
        "sfx": {0: "hoofbeats"},
        "thumb_scene": "01_match",
        "scenes": [
            {"id": "01_match", "seed": 1859,
             "flux_prompt": "A polo match in 1880s India, riders on galloping ponies swinging mallets, dust and action, colonial pavilion in the background, wide action shot, " + _K,
             "motion_prompt": "the ponies gallop after the ball, a rider swings his mallet, dust rises",
             "caption": "India, 1859.\nOfficers fell for a fast game.",
             "eyebrow": "A TRUE STORY"},
            {"id": "02_collar", "seed": 1860,
             "flux_prompt": "Close-up of a polo player's shirt collar flapping wildly in the wind as he rides, frustrated expression, motion and speed, " + _K,
             "motion_prompt": "the collar flaps hard in the wind against his face as he rides",
             "caption": "One enemy ruined every match:\nthe flapping collar.",
             "eyebrow": "THE PROBLEM"},
            {"id": "03_button", "seed": 1861,
             "flux_prompt": "Close-up of hands buttoning down a shirt collar point, neat white pique cotton shirt on a table, soft daylight, " + _K,
             "motion_prompt": "the fingers fasten the small collar button, smooth the collar flat",
             "caption": "So they buttoned it down.\nQuietly genius.",
             "eyebrow": "THE FIX"},
            {"id": "04_lacoste", "seed": 1862,
             "flux_prompt": "A 1920s tennis player in a short-sleeved white pique shirt serving on a grass court, crowd in period dress watching, " + _K,
             "motion_prompt": "he tosses the ball and serves, the crowd turns to follow",
             "caption": "A tennis rebel cut the sleeves\nand wore a crocodile.",
             "eyebrow": "THE REBEL"},
            {"id": "05_campus", "seed": 1863,
             "flux_prompt": "Young people in colorful polo shirts laughing on a 1950s American college campus, bicycles and books, bright cheerful light, " + _K,
             "motion_prompt": "they walk and laugh together, one spins a book in his hand",
             "caption": "From pitch to campus,\nit conquered casual.",
             "eyebrow": "THE SPREAD"},
            {"id": "06_empire", "seed": 1864,
             "flux_prompt": "Rows of neatly folded colorful polo shirts in a bright modern store display, every color of the rainbow, " + _K,
             "motion_prompt": "light drifts across the folded shirts, subtle camera push in",
             "caption": "Two billion sold a year.\nBorn on horseback.",
             "eyebrow": "THE EMPIRE"},
        ],
    },

    # ── GUCCI HORSEBIT ──────────────────────────────────────────────
    "the-gucci-horsebit-loafer-born-in-the-saddle": {
        "title_lines": ("THE BIT THAT", "LEFT THE STABLE"),
        "subtitle": "Florence, 1953",
        "mood": "elegant_waltz",
        "band_in": 2,
        "sfx": {0: "hoofbeats", 2: "ticks"},
        "thumb_scene": "03_loafer",
        "scenes": [
            {"id": "01_bridle", "seed": 1953,
             "flux_prompt": "Close-up of a racehorse's bridle with a gleaming metal snaffle bit, groom's hands adjusting it, stable interior, warm light, " + _K,
             "motion_prompt": "the horse tosses its head gently, the metal bit catches the light",
             "caption": "Florence, 1953.\nGuccio knew stables.",
             "eyebrow": "A TRUE STORY"},
            {"id": "02_porter", "seed": 1954,
             "flux_prompt": "A young hotel porter carrying elegant leather luggage through a grand 1900s London hotel lobby, marble and brass, wealthy guests, " + _K,
             "motion_prompt": "the porter walks through the lobby carrying the cases, guests pass by",
             "caption": "A porter in London studied\nwhat the rich carried.",
             "eyebrow": "THE EDUCATION"},
            {"id": "03_loafer", "seed": 1955,
             "flux_prompt": "A Florentine shoemaker's workshop, hands fitting a small metal horsebit ornament across a black leather loafer, lasts and tools around, " + _K,
             "motion_prompt": "the hands position the metal bit on the loafer, press it into place",
             "caption": "He set a snaffle bit\nacross a loafer's tongue.",
             "eyebrow": "THE IDEA"},
            {"id": "04_boardroom", "seed": 1956,
             "flux_prompt": "A confident 1960s businessman in a sharp suit and black horsebit loafers striding across a marble plaza, briefcase in hand, " + _K,
             "motion_prompt": "he strides confidently across the plaza, the loafers flash with each step",
             "caption": "Bankers wore the stable\ninto the boardroom.",
             "eyebrow": "THE TAKEOVER"},
            {"id": "05_museum", "seed": 1957,
             "flux_prompt": "A single black leather horsebit loafer displayed in a museum glass vitrine under a spotlight, minimalist gallery, " + _K,
             "motion_prompt": "the spotlight gleams across the leather, reflections shift on the glass",
             "caption": "MoMA keeps one\nin its collection.",
             "eyebrow": "THE ARTIFACT"},
            {"id": "06_street", "seed": 1958,
             "flux_prompt": "Street-style shot of loafers stepping across a crosswalk at fashion week, stylish trousers, city motion, " + _K,
             "motion_prompt": "the feet stride across the crosswalk, the city moves behind",
             "caption": "Two rings and a bar —\nfashion's quietest flex.",
             "eyebrow": "THE SIGNATURE"},
        ],
    },

    # ── RIDING BOOTS ────────────────────────────────────────────────
    "riding-boots-from-cavalry-to-catwalk": {
        "title_lines": ("A THOUSAND YEARS", "OF TALL LEATHER"),
        "subtitle": "From cavalry to catwalk",
        "mood": "elegant_waltz",
        "band_in": 1,
        "sfx": {0: "hoofbeats", 1: "hoofbeats", 3: "hoofbeats"},
        "thumb_scene": "01_charge",
        "scenes": [
            {"id": "01_charge", "seed": 801,
             "flux_prompt": "A cavalry charge across a misty field at dawn, riders in tall black boots and uniforms, sabers drawn, dramatic wide shot, " + _K,
             "motion_prompt": "the cavalry charges forward through the mist, horses at full gallop",
             "caption": "Before fashion,\nboots went to war.",
             "eyebrow": "A TRUE STORY"},
            {"id": "02_stirrup", "seed": 802,
             "flux_prompt": "Close-up of an officer's tall polished black boot in a brass stirrup, spur glinting, horse's flank, " + _K,
             "motion_prompt": "the horse walks, the boot flexes in the stirrup, the spur catches light",
             "caption": "Tall leather gripped the stirrup\nand saved the leg.",
             "eyebrow": "THE TOOL"},
            {"id": "03_duke", "seed": 803,
             "flux_prompt": "A distinguished 1810s officer in a dark coat and polished tall boots standing beside his horse, portrait composition, stately light, " + _K,
             "motion_prompt": "he adjusts his glove, the horse shifts beside him",
             "caption": "A duke gave his name\nto a boot.",
             "eyebrow": "THE DUKE"},
            {"id": "04_hunt", "seed": 804,
             "flux_prompt": "Riders in hunt attire jumping a hedge in the English countryside, tall boots and red coats, hounds running, misty morning, " + _K,
             "motion_prompt": "a horse clears the hedge, hounds stream underneath, riders follow",
             "caption": "The hunt made them\na uniform of privilege.",
             "eyebrow": "THE HUNT"},
            {"id": "05_catwalk", "seed": 805,
             "flux_prompt": "A 1960s fashion model striding down a city street in sleek black riding boots and a mod coat, confident, photographers behind, " + _K,
             "motion_prompt": "she strides toward the camera, coat swinging, flashbulbs pop behind her",
             "caption": "Then the catwalk stole\nthe cavalry's look.",
             "eyebrow": "THE THEFT"},
            {"id": "06_legacy", "seed": 806,
             "flux_prompt": "A row of elegant tall leather riding boots in a warm boutique window at dusk, brass fittings, soft golden display light, " + _K,
             "motion_prompt": "the display light glows, reflections drift across the polished leather",
             "caption": "From cavalry to catwalk —\nnever out of step.",
             "eyebrow": "THE LEGACY"},
        ],
    },

    # ── RIDING CROP ─────────────────────────────────────────────────
    "the-riding-crop-from-horse-command-to-fashion-icon": {
        "title_lines": ("THE LANGUAGE", "OF THE CROP"),
        "subtitle": "Two thousand years of command",
        "mood": "elegant_waltz",
        "band_in": 2,
        "sfx": {0: "hoofbeats", 2: "ticks", 3: "hoofbeats"},
        "thumb_scene": "04_dressage",
        "scenes": [
            {"id": "01_rome", "seed": 100,
             "flux_prompt": "A Roman cavalry officer on horseback holding a short leather baton, legionaries marching behind, ancient road, dramatic light, " + _K,
             "motion_prompt": "the horse steps proudly, the officer raises the baton to signal",
             "caption": "Rome, 100 AD.\nOrders traveled by leather.",
             "eyebrow": "A TRUE STORY"},
            {"id": "02_knight", "seed": 200,
             "flux_prompt": "A medieval knight on an armored warhorse at a tournament, holding a leather crop, banners fluttering, castle walls behind, " + _K,
             "motion_prompt": "the banners flutter, the warhorse paws the ground, the knight steadies it",
             "caption": "Knights spoke to warhorses\nwithout a word.",
             "eyebrow": "THE CODE"},
            {"id": "03_workshop", "seed": 1750,
             "flux_prompt": "A London craftsman's workshop in 1750, hands braiding a fine leather riding crop, spools of leather lace, candlelight, close shot, " + _K,
             "motion_prompt": "the hands braid the leather strands in a steady rhythm",
             "caption": "Swaine Adeney has braided\nthem since 1750.",
             "eyebrow": "THE HOUSE"},
            {"id": "04_dressage", "seed": 400,
             "flux_prompt": "A dressage horse and rider performing in a formal arena, perfect posture, the rider holding a slim crop, elegant precision, soft daylight, " + _K,
             "motion_prompt": "the horse performs an elevated trot, precise and graceful, the rider sits motionless",
             "caption": "In dressage, the crop is\npunctuation, not force.",
             "eyebrow": "THE ART"},
            {"id": "05_fashion", "seed": 500,
             "flux_prompt": "An elegant equestrienne in tweed jacket and leather gloves holding a riding crop, stable yard background, editorial portrait, " + _K,
             "motion_prompt": "she turns slightly toward the camera, tapping the crop against her glove",
             "caption": "Fashion borrowed the gesture\nof command.",
             "eyebrow": "THE SYMBOL"},
            {"id": "06_still", "seed": 600,
             "flux_prompt": "A still life of a braided leather riding crop resting across leather gloves and a saddle, warm window light, quiet elegance, " + _K,
             "motion_prompt": "the window light shifts slowly across the leather, dust motes drift",
             "caption": "A conversation between\nrider and horse, refined.",
             "eyebrow": "THE LANGUAGE"},
        ],
    },

    # ── BELSTAFF: one storm, one jacket, one inheritance ────────────
    "belstaff-the-jacket-that-built-a-riding-legend": {
        "title_lines": ("BELSTAFF", "EST. 1924"),
        "subtitle": "The jacket that refused the rain",
        "mood": "storm_heritage",
        "band_in": 2,
        "smooth": True,
        "sfx": {0: ["wind"], 1: ["ticks"], 2: ["rain", "engine"],
                3: ["rain"], 4: ["rain"]},
        "thumb_scene": "04_shedding",
        "scenes": [
            {"id": "01_storm", "seed": 2401,
             "flux_prompt": "Dark storm clouds gathering over the English moors, a lone motorcyclist in a belted waxed-cotton jacket standing beside his vintage motorcycle looking toward the weather, wind-blown grass, brooding overcast light, candid documentary photograph, " + _K,
             "motion_prompt": "storm clouds roll and darken, the jacket and grass flap in the rising wind, the rider watches the horizon",
             "caption": "England, 1924.\nBelstaff made one promise.",
             "eyebrow": "BELSTAFF • EST. 1924"},
            {"id": "02_wax", "seed": 2402,
             "flux_prompt": "Weathered hands brushing warm amber wax into heavy cotton cloth on a scarred wooden workbench in a dim Stoke-on-Trent mill, tins of wax and brushes, single work lamp, honest working atmosphere, candid documentary photograph, " + _K,
             "motion_prompt": "the brush works the wax into the cloth in slow strokes, the fabric darkens and gleams",
             "caption": "Cotton, taught to drink wax\nin a Stoke-on-Trent mill.",
             "eyebrow": "THE PROMISE"},
            {"id": "03_downpour", "seed": 2403,
             "flux_prompt": "A motorcyclist in a belted waxed jacket riding through heavy night rain on a dark moorland road, headlight beam cutting through sheets of rain, spray from the wheels, grim determination, realistic wet night photography, " + _K,
             "motion_prompt": "the motorcycle pushes through the driving rain, the headlight beam sweeps, spray flies from the wheels",
             "caption": "The storm came for him\nan hour from home.",
             "eyebrow": "THE TEST"},
            {"id": "04_shedding", "seed": 2404,
             "flux_prompt": "Extreme close-up of rain beading and rolling off the shoulder of a waxed-cotton motorcycle jacket at night, water droplets streaming off the waxed surface, headlight glow behind the rain, macro realism, " + _K,
             "motion_prompt": "raindrops hit the waxed shoulder and bead away, water streams off the surface",
             "caption": "The rain rolled off.\nThe rider rode on.",
             "eyebrow": "THE PROOF"},
            {"id": "05_home", "seed": 2405,
             "flux_prompt": "A motorcyclist pulling up outside a warm-lit stone cottage in the rain at night, golden light from the windows on the wet cobbles, dismounting stiffly but safe, homely refuge, candid documentary photograph, " + _K,
             "motion_prompt": "the motorcycle stops on the wet cobbles, the rider dismounts, rain falls through the warm window light",
             "caption": "He arrived soaked in storm —\nand dry at the heart.",
             "eyebrow": "HOME"},
            {"id": "06_heirloom", "seed": 2406,
             "flux_prompt": "An elderly man handing his worn waxed-cotton jacket with decades of patina to his adult son in a warm workshop, both hands on the jacket between them, tender weighty moment, warm side light, candid documentary photograph, " + _K,
             "motion_prompt": "the father passes the jacket into his son's hands, the son takes its weight, they hold the moment",
             "caption": "Forty years on, he handed\nthe same jacket to his son.",
             "eyebrow": "THE HEIRLOOM"},
        ],
    },
}
